<?php

namespace App\Models;

use CodeIgniter\Model;

/**
 * Uploaded verification documents. Paths here are relative to the private
 * storage root, NOT to FCPATH — these files are deliberately not web-served.
 */
class DirectoryVerificationDocumentModel extends Model
{
    protected $table         = 'xs_directory_verification_documents';
    protected $primaryKey    = 'id';
    protected $returnType    = 'array';
    protected $useTimestamps = true;
    protected $allowedFields = [
        'verification_id', 'submission_id', 'kind', 'path', 'original_name',
        'mime', 'bytes', 'sha256', 'superseded_at',
    ];

    public const KIND_REGISTRATION = 'company_registration';
    public const KIND_OWNER_ID     = 'owner_id';

    public const KINDS = [self::KIND_REGISTRATION, self::KIND_OWNER_ID];

    /** Human labels, in the order the review queue and the owner form show them. */
    public const KIND_LABELS = [
        self::KIND_REGISTRATION => 'Company registration document',
        self::KIND_OWNER_ID     => 'Owner ID document',
    ];

    /**
     * Where uploaded documents live: outside the docroot, so no web server
     * config change can accidentally expose them. Kept as a method rather than
     * a const because WRITEPATH is only defined once the framework boots.
     */
    public static function storageRoot(): string
    {
        return rtrim(WRITEPATH, '/\\') . '/verification';
    }

    /**
     * The documents behind the application currently in play.
     *
     * Superseded rows are excluded, which is what keeps the review queue and the
     * owner's panel showing one registration document and one ID rather than a
     * growing pile of every attempt. Their files are still on disk and still
     * streamable by id — see historyForVerification().
     *
     * @return array<int,array<string,mixed>>
     */
    public function forVerification(int $verificationId): array
    {
        return $this->where('verification_id', $verificationId)
            ->where('superseded_at', null)
            ->orderBy('kind', 'ASC')
            ->orderBy('id', 'ASC')
            ->findAll();
    }

    /**
     * Every document ever attached to this verification, superseded ones
     * included, oldest attempt first.
     *
     * @return array<int,array<string,mixed>>
     */
    public function historyForVerification(int $verificationId): array
    {
        return $this->where('verification_id', $verificationId)
            ->orderBy('submission_id', 'ASC')
            ->orderBy('kind', 'ASC')
            ->orderBy('id', 'ASC')
            ->findAll();
    }

    /**
     * The superseded documents only, grouped by the application they belonged
     * to, for the "earlier attempts" panel in the review queue.
     *
     * @return array<int,array<int,array<string,mixed>>> keyed by submission id
     */
    public function supersededBySubmission(int $verificationId): array
    {
        $rows = $this->where('verification_id', $verificationId)
            ->where('superseded_at IS NOT NULL')
            ->orderBy('submission_id', 'ASC')
            ->orderBy('kind', 'ASC')
            ->findAll();

        $out = [];
        foreach ($rows as $row) {
            $out[(int) ($row['submission_id'] ?? 0)][] = $row;
        }

        return $out;
    }

    /**
     * Mark this verification's live documents as replaced by a newer
     * application. The files stay on disk for now so a reviewer can still see
     * what the earlier attempt looked like; purgeSuperseded() removes them once
     * that grace period is up.
     */
    public function supersedeForVerification(int $verificationId): void
    {
        $live = $this->forVerification($verificationId);
        if ($live === []) {
            return;
        }

        $this->whereIn('id', array_column($live, 'id'))
            ->set('superseded_at', date('Y-m-d H:i:s'))
            ->update();
    }

    /**
     * Absolute path of a stored document, or null if it does not resolve to a
     * real file inside the storage root.
     *
     * Every consumer — the streaming route and the delete path — goes through
     * this one function, so the containment check cannot be forgotten by one of
     * them. Paths are generated by VerificationDocumentProcessor and never come
     * from a request, but a row is still data, and data can be wrong.
     */
    public function resolvePath(string $path): ?string
    {
        $path = ltrim(trim($path), '/');
        if ($path === '' || str_contains($path, "\0")) {
            return null;
        }

        $root = realpath(self::storageRoot());
        if ($root === false) {
            return null;
        }
        $root = rtrim($root, '/');

        $full = realpath($root . '/' . $path);

        if ($full === false || ! str_starts_with($full, $root . '/') || ! is_file($full)) {
            return null;
        }

        return $full;
    }

    /**
     * Delete a document row and the file behind it.
     *
     * @param array<string,mixed> $doc a row from this table
     */
    public function deleteWithFile(array $doc): void
    {
        $this->deleteFileAt((string) ($doc['path'] ?? ''));
        $this->delete((int) $doc['id']);
    }

    /**
     * Delete every document for a verification, files included — superseded
     * attempts as well as the live one.
     *
     * The only caller left is the listing purge, and that is the point: this is
     * where the retention boundary is enforced, so it has to see everything.
     * historyForVerification(), not forVerification() — the latter filters out
     * superseded rows, and using it here would quietly leave the earlier
     * attempts' ID copies on disk with no row pointing at them and nothing that
     * would ever come back for them.
     *
     * Re-submission no longer comes through here; it calls
     * supersedeForVerification() instead.
     */
    public function deleteForVerification(int $verificationId): void
    {
        foreach ($this->historyForVerification($verificationId) as $doc) {
            $this->deleteWithFile($doc);
        }
    }

    /**
     * Purge documents that were replaced by a later application, once they are
     * older than $days.
     *
     * supersedeForVerification() deliberately leaves the files on disk so a
     * reviewer can still see what an earlier attempt looked like. That is a
     * grace period, not a retention decision — an ID copy the owner has already
     * replaced has no reason to outlive the review it informed. This is the
     * back half of that pair.
     *
     * @return int documents deleted
     */
    public function purgeSuperseded(int $days): int
    {
        $cutoff = date('Y-m-d H:i:s', strtotime('-' . $days . ' days'));

        $stale = $this->where('superseded_at IS NOT NULL')
            ->where('superseded_at <', $cutoff)
            ->findAll();

        foreach ($stale as $doc) {
            $this->deleteWithFile($doc);
        }

        return count($stale);
    }

    /**
     * Purge documents belonging to verifications that ended more than $days ago.
     *
     * "Ended" means lapsed or rejected — never active, approved or submitted, so
     * a paying badge holder never loses the evidence behind their own badge. The
     * end date is whichever of paid_until / reviewed_at / updated_at is present:
     * a lapsed subscription ends when its cover ran out, a rejected application
     * when it was reviewed, and updated_at is the backstop for rows that predate
     * either being set.
     *
     * Deliberately not a listing delete: that path already exists in
     * DirectoryAdminService and removes everything at once. This one is the
     * time-based boundary for listings that stay but whose badge did not.
     *
     * @return int documents deleted
     */
    public function purgeForEndedVerifications(int $days): int
    {
        $cutoff = date('Y-m-d H:i:s', strtotime('-' . $days . ' days'));
        $table  = $this->db->prefixTable('directory_verifications');

        // Raw COALESCE with an escaped literal: the query builder would treat
        // the whole expression as an identifier and quote it into nonsense.
        $rows = $this->db->table($table)
            ->select('id')
            ->whereIn('state', [
                DirectoryVerificationModel::STATE_LAPSED,
                DirectoryVerificationModel::STATE_REJECTED,
            ])
            ->where('COALESCE(paid_until, reviewed_at, updated_at) < ' . $this->db->escape($cutoff))
            ->get()
            ->getResultArray();

        if ($rows === []) {
            return 0;
        }

        $deleted = 0;
        foreach (array_column($rows, 'id') as $verificationId) {
            foreach ($this->historyForVerification((int) $verificationId) as $doc) {
                $this->deleteWithFile($doc);
                $deleted++;
            }
        }

        return $deleted;
    }

    /**
     * Silently does nothing when the path does not resolve inside the storage
     * root: this runs during cleanup, where refusing to delete is always the
     * safe failure.
     */
    public function deleteFileAt(string $path): void
    {
        $full = $this->resolvePath($path);
        if ($full !== null) {
            @unlink($full);
        }
    }
}
