<?php

namespace App\Models;

use CodeIgniter\Model;

/**
 * Uploaded verification documents. Paths here are relative to the private
 * storage root, NOT to FCPATH — these files are deliberately not web-served.
 */
class DirectoryVerificationDocumentModel extends Model
{
    protected $table         = 'xs_directory_verification_documents';
    protected $primaryKey    = 'id';
    protected $returnType    = 'array';
    protected $useTimestamps = true;
    protected $allowedFields = [
        'verification_id', 'submission_id', 'kind', 'path', 'original_name',
        'mime', 'bytes', 'sha256', 'superseded_at',
    ];

    public const KIND_REGISTRATION = 'company_registration';
    public const KIND_OWNER_ID     = 'owner_id';

    public const KINDS = [self::KIND_REGISTRATION, self::KIND_OWNER_ID];

    /** Human labels, in the order the review queue and the owner form show them. */
    public const KIND_LABELS = [
        self::KIND_REGISTRATION => 'Company registration document',
        self::KIND_OWNER_ID     => 'Owner ID document',
    ];

    /**
     * Where uploaded documents live: outside the docroot, so no web server
     * config change can accidentally expose them. Kept as a method rather than
     * a const because WRITEPATH is only defined once the framework boots.
     */
    public static function storageRoot(): string
    {
        return rtrim(WRITEPATH, '/\\') . '/verification';
    }

    /**
     * The documents behind the application currently in play.
     *
     * Superseded rows are excluded, which is what keeps the review queue and the
     * owner's panel showing one registration document and one ID rather than a
     * growing pile of every attempt. Their files are still on disk and still
     * streamable by id — see historyForVerification().
     *
     * @return array<int,array<string,mixed>>
     */
    public function forVerification(int $verificationId): array
    {
        return $this->where('verification_id', $verificationId)
            ->where('superseded_at', null)
            ->orderBy('kind', 'ASC')
            ->orderBy('id', 'ASC')
            ->findAll();
    }

    /**
     * Every document ever attached to this verification, superseded ones
     * included, oldest attempt first.
     *
     * @return array<int,array<string,mixed>>
     */
    public function historyForVerification(int $verificationId): array
    {
        return $this->where('verification_id', $verificationId)
            ->orderBy('submission_id', 'ASC')
            ->orderBy('kind', 'ASC')
            ->orderBy('id', 'ASC')
            ->findAll();
    }

    /**
     * The superseded documents only, grouped by the application they belonged
     * to, for the "earlier attempts" panel in the review queue.
     *
     * @return array<int,array<int,array<string,mixed>>> keyed by submission id
     */
    public function supersededBySubmission(int $verificationId): array
    {
        $rows = $this->where('verification_id', $verificationId)
            ->where('superseded_at IS NOT NULL')
            ->orderBy('submission_id', 'ASC')
            ->orderBy('kind', 'ASC')
            ->findAll();

        $out = [];
        foreach ($rows as $row) {
            $out[(int) ($row['submission_id'] ?? 0)][] = $row;
        }

        return $out;
    }

    /**
     * Mark this verification's live documents as replaced by a newer
     * application. The files are deliberately left on disk: the retention
     * boundary is the life of the listing, not the life of one attempt.
     */
    public function supersedeForVerification(int $verificationId): void
    {
        $live = $this->forVerification($verificationId);
        if ($live === []) {
            return;
        }

        $this->whereIn('id', array_column($live, 'id'))
            ->set('superseded_at', date('Y-m-d H:i:s'))
            ->update();
    }

    /**
     * Absolute path of a stored document, or null if it does not resolve to a
     * real file inside the storage root.
     *
     * Every consumer — the streaming route and the delete path — goes through
     * this one function, so the containment check cannot be forgotten by one of
     * them. Paths are generated by VerificationDocumentProcessor and never come
     * from a request, but a row is still data, and data can be wrong.
     */
    public function resolvePath(string $path): ?string
    {
        $path = ltrim(trim($path), '/');
        if ($path === '' || str_contains($path, "\0")) {
            return null;
        }

        $root = realpath(self::storageRoot());
        if ($root === false) {
            return null;
        }
        $root = rtrim($root, '/');

        $full = realpath($root . '/' . $path);

        if ($full === false || ! str_starts_with($full, $root . '/') || ! is_file($full)) {
            return null;
        }

        return $full;
    }

    /**
     * Delete a document row and the file behind it.
     *
     * @param array<string,mixed> $doc a row from this table
     */
    public function deleteWithFile(array $doc): void
    {
        $this->deleteFileAt((string) ($doc['path'] ?? ''));
        $this->delete((int) $doc['id']);
    }

    /**
     * Delete every document for a verification, files included — superseded
     * attempts as well as the live one.
     *
     * The only caller left is the listing purge, and that is the point: this is
     * where the retention boundary is enforced, so it has to see everything.
     * historyForVerification(), not forVerification() — the latter filters out
     * superseded rows, and using it here would quietly leave the earlier
     * attempts' ID copies on disk with no row pointing at them and nothing that
     * would ever come back for them.
     *
     * Re-submission no longer comes through here; it calls
     * supersedeForVerification() instead.
     */
    public function deleteForVerification(int $verificationId): void
    {
        foreach ($this->historyForVerification($verificationId) as $doc) {
            $this->deleteWithFile($doc);
        }
    }

    /**
     * Silently does nothing when the path does not resolve inside the storage
     * root: this runs during cleanup, where refusing to delete is always the
     * safe failure.
     */
    public function deleteFileAt(string $path): void
    {
        $full = $this->resolvePath($path);
        if ($full !== null) {
            @unlink($full);
        }
    }
}
