<?php

namespace App\Models;

use CodeIgniter\Model;

/**
 * Uploaded verification documents. Paths here are relative to the private
 * storage root, NOT to FCPATH — these files are deliberately not web-served.
 */
class DirectoryVerificationDocumentModel extends Model
{
    protected $table         = 'xs_directory_verification_documents';
    protected $primaryKey    = 'id';
    protected $returnType    = 'array';
    protected $useTimestamps = true;
    protected $allowedFields = [
        'verification_id', 'kind', 'path', 'original_name', 'mime', 'bytes',
    ];

    public const KIND_REGISTRATION = 'company_registration';
    public const KIND_OWNER_ID     = 'owner_id';

    public const KINDS = [self::KIND_REGISTRATION, self::KIND_OWNER_ID];

    /** Human labels, in the order the review queue and the owner form show them. */
    public const KIND_LABELS = [
        self::KIND_REGISTRATION => 'Company registration document',
        self::KIND_OWNER_ID     => 'Owner ID document',
    ];

    /**
     * Where uploaded documents live: outside the docroot, so no web server
     * config change can accidentally expose them. Kept as a method rather than
     * a const because WRITEPATH is only defined once the framework boots.
     */
    public static function storageRoot(): string
    {
        return rtrim(WRITEPATH, '/\\') . '/verification';
    }

    /**
     * @return array<int,array<string,mixed>>
     */
    public function forVerification(int $verificationId): array
    {
        return $this->where('verification_id', $verificationId)
            ->orderBy('kind', 'ASC')
            ->orderBy('id', 'ASC')
            ->findAll();
    }

    /**
     * Absolute path of a stored document, or null if it does not resolve to a
     * real file inside the storage root.
     *
     * Every consumer — the streaming route and the delete path — goes through
     * this one function, so the containment check cannot be forgotten by one of
     * them. Paths are generated by VerificationDocumentProcessor and never come
     * from a request, but a row is still data, and data can be wrong.
     */
    public function resolvePath(string $path): ?string
    {
        $path = ltrim(trim($path), '/');
        if ($path === '' || str_contains($path, "\0")) {
            return null;
        }

        $root = realpath(self::storageRoot());
        if ($root === false) {
            return null;
        }
        $root = rtrim($root, '/');

        $full = realpath($root . '/' . $path);

        if ($full === false || ! str_starts_with($full, $root . '/') || ! is_file($full)) {
            return null;
        }

        return $full;
    }

    /**
     * Delete a document row and the file behind it.
     *
     * @param array<string,mixed> $doc a row from this table
     */
    public function deleteWithFile(array $doc): void
    {
        $this->deleteFileAt((string) ($doc['path'] ?? ''));
        $this->delete((int) $doc['id']);
    }

    /**
     * Delete every document for a verification, files included. Used when an
     * owner re-submits after a rejection: the superseded evidence should not
     * outlive the application it belonged to.
     */
    public function deleteForVerification(int $verificationId): void
    {
        foreach ($this->forVerification($verificationId) as $doc) {
            $this->deleteWithFile($doc);
        }
    }

    /**
     * Silently does nothing when the path does not resolve inside the storage
     * root: this runs during cleanup, where refusing to delete is always the
     * safe failure.
     */
    public function deleteFileAt(string $path): void
    {
        $full = $this->resolvePath($path);
        if ($full !== null) {
            @unlink($full);
        }
    }
}
